"""Initial migration

Revision ID: 6a30bcac59c9
Revises: 
Create Date: 2026-02-10 20:39:51.757312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a30bcac59c9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gap_map_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Unique identifier for the gap map entry'),
    sa.Column('title', sa.String(), nullable=False, comment='Title of the research gap or problem'),
    sa.Column('description', sa.Text(), nullable=True, comment='Detailed description of the gap'),
    sa.Column('source', sa.String(), nullable=False, comment='Source database: convergent, homeworld, wikenigma, 3ie, encyclopedia'),
    sa.Column('source_url', sa.String(), nullable=False, comment='URL to the original entry in the source database'),
    sa.Column('category', sa.String(), nullable=True, comment='Category or domain of the research gap'),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True, comment='Tags or keywords associated with this gap (PostgreSQL array)'),
    sa.Column('scraped_at', sa.DateTime(), nullable=False, comment='When this entry was last scraped from the source'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='When this record was first created in our database'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='When this record was last updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_category', 'gap_map_entries', ['category'], unique=False)
    op.create_index('idx_scraped_at', 'gap_map_entries', ['scraped_at'], unique=False)
    op.create_index('idx_source', 'gap_map_entries', ['source'], unique=False)
    op.create_index('idx_source_category', 'gap_map_entries', ['source', 'category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_source_category', table_name='gap_map_entries')
    op.drop_index('idx_source', table_name='gap_map_entries')
    op.drop_index('idx_scraped_at', table_name='gap_map_entries')
    op.drop_index('idx_category', table_name='gap_map_entries')
    op.drop_table('gap_map_entries')
    # ### end Alembic commands ###
